#!/usr/bin/env bash

# Get latest version in Storage
LATEST_VERSION=$(gsutil ls gs://ubiquitous-goggles-bucket/football-prediction/ | awk '{ print substr( $0, 53) }' | sed 's/.$//' | sed 1,1d | sort -n | tail -1)

# Write to a file so we read it
echo $LATEST_VERSION > latest_version.txt