CREATE TABLE IF NOT EXISTS h2h.general (
    id VARCHAR(12), 
    league_id VARCHAR(12), 
    season_id VARCHAR(12), 
    stage_id VARCHAR(12), 
    round_id VARCHAR(12), 
    group_id VARCHAR(12),
    aggregate_id VARCHAR(12), 
    venue_id VARCHAR(12), 
    referee_id VARCHAR(12), 
    localteam_id VARCHAR(12),
    visitorteam_id VARCHAR(12),
    winner_team_id VARCHAR(12),
    commentaries VARCHAR(7),
    attendance VARCHAR(7),
    pitch VARCHAR(30),
    neutral_venue VARCHAR(100),
    winning_odds_calculated VARCHAR(7),
    leg VARCHAR(10),
    deleted VARCHAR(7),
    is_placeholder VARCHAR(7),
    UNIQUE KEY  (`id`)
);
